### PR TITLE
Spelling ui changes

### PR DESCRIPTION
**Pull request by michaelyfan**
### Description
Some minor UI changes and one bugfix. Modified homepage image to make "Clubs" singular; fixed word overflow in Projects section of homepage; fixed a navbar link on Teams page.

### How to Test
1. Clone this branch
1. Start a local instance of the site with `dev_appserver.py app.yaml `
    1. If this is not working for you, make sure you've followed instructions under this project's README's "Installing Google Cloud SDK" section.
1. navigate to localhost:8080 and verify that the mentioned changes in the homepage and the team page have been applied

### CODE REVIEW

**Comment by tujson** [comment]
LGTM

**Review by tujson — APPROVED** [review]
LGTM

**Comment by michaelyfan** [comment]
Will this deploy automatically upon merge, or will you be doing that manually? @tujson

**Comment by tujson** [comment]
> Will this deploy automatically upon merge, or will you be doing that manually? @tujson

Now it'll deploy automatically :).

**Comment by michaelyfan** [comment]
> 
> 
> > Will this deploy automatically upon merge, or will you be doing that manually? @tujson
> 
> Now it'll deploy automatically :).

very nice

**Pull request merged**
